In [2]:
# import required libraries
import tensorflow as tf

In [17]:
# declare a list of random values
daily_sales = [23, 45, 11, -1, -34, 0, 12, 33]

In [18]:
# make a pipeline using tensorflow
dataset = tf.data.Dataset.from_tensor_slices(daily_sales)

In [19]:
dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [20]:
# iterate through dataset and show elements
for element in dataset:
    print(element.numpy())

23
45
11
-1
-34
0
12
33


In [21]:
# if want to show selected no of elements
for i in dataset.take(3):
    print(i.numpy())

23
45
11


In [22]:
# now remove negative values from dataset
dataset = dataset.filter(lambda x: x >= 0)

In [23]:
# iterate again and check
for j in dataset.as_numpy_iterator():
    print(j)

23
45
11
0
12
33


In [24]:
# convert above data to pkr as it is in usd
dataset = dataset.map(lambda y: y*279)

In [25]:
for k in dataset.as_numpy_iterator():
    print(k)

6417
12555
3069
0
3348
9207


In [28]:
# shuffle data elements
dataset = dataset.shuffle(2)

for m in dataset.as_numpy_iterator():
    print(m)

0
9207
3348
6417
12555
3069


In [31]:
# we can create batches 

for j in dataset.batch(3):
    print(j.numpy())

[3069 6417 3348]
[ 9207     0 12555]


In [36]:
# combine all the above operations in just one line and make a pipeline
dataset_pipe = tf.data.Dataset.from_tensor_slices(daily_sales)
dataset_pipe = dataset_pipe.filter(lambda x: x >= 0).map(lambda y: y*279).shuffle(2).batch(3)

In [37]:
dataset_pipe

<_BatchDataset element_spec=TensorSpec(shape=(None,), dtype=tf.int32, name=None)>

In [38]:
for i in dataset_pipe:
    print(i.numpy())

[ 6417  3069 12555]
[   0 9207 3348]
